// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbcqlbpvpqucdzobxjjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iY3FsYnB2cHF1Y2R6b2J4amp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDEzMDAsImV4cCI6MjA1Nzk3NzMwMH0.8Z0QTr7hl8uhpdSbfTdw3AqG0l3U5-c9krdpTBaJeOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);